// packages-vue/vue-element-plus-extra/src/dialog/ui/rc/footer/index.vue
<script lang="ts" setup>

import {
  computed,
  isVNode
} from "vue";
import{
  ElSpace,
  ElButton
} from "element-plus";

import {
  isObject
} from "@mt-kit/utils";

import {
  usePropsOk,
  usePropsCancel,
  usePropsIsSubmit,
  usePropsFooterExtra,
  useHandleOnClose,
  useHandleOnSubmit,
  useStateLocked,
  ModelLockState
} from "../../../model";

const ok = usePropsOk();

const okButtonProps = computed(() => {
  return (isObject(ok.value) ? {
    ...ok.value
  } : {
    label: ok.value
  });
});

const cancel = usePropsCancel();

const cancelButtonProps = computed(() => {
  return (isObject(cancel.value) ? {
    ...cancel.value
  } : {
    label: cancel.value
  });
});

const isSubmit = usePropsIsSubmit();

const footerExtra = usePropsFooterExtra();

const handleClose = useHandleOnClose();

const handleOnSubmit = useHandleOnSubmit();

const locked = useStateLocked();

</script>
<template>
  <ElSpace>
    <component
      :is="footerExtra"
      v-if="isVNode(footerExtra)"
    />
    <template v-else>
      {{ footerExtra }}
    </template>

    <ElButton
      v-bind="cancelButtonProps"
      @click="handleClose"
    >
      {{ cancelButtonProps?.label || "关闭" }}
    </ElButton>

    <!--
 是否进行提交操作, false 时只显示关闭 - 查看/详情
-->
    <ElButton
      v-if="isSubmit"
      type="primary"
      :loading="locked === ModelLockState.LOADING"
      v-bind="okButtonProps"
      @click="handleOnSubmit"
    >
      {{ okButtonProps?.label || "提交" }}
    </ElButton>
  </ElSpace>
</template>

// packages-react/react-ant-design-extra/src/rc-dialog/ui/rc/footer/index.tsx
import React, {
  useMemo,
  MouseEvent
} from "react";
import {
  Button,
  Space
} from "antd";

import {
  useHandleOnClose,
  useHandleOnSubmit,
  useStateLocked,
  ModelLockState,
  usePropsFooterExtra,
  usePropsOk,
  usePropsCancel,
  usePropsIsSubmit
} from "../../../model";

export default function Footer(): React.ReactElement {
  const handleOnClose = useHandleOnClose();

  const handleOnSubmit = useHandleOnSubmit();

  const locked = useStateLocked();

  const footerExtra = usePropsFooterExtra();

  const ok = usePropsOk();

  const isSubmit = usePropsIsSubmit();

  const okButtonProps = useMemo(() => {
    return (typeof ok === "object" ? {
      ...ok,
      onClick: (event: MouseEvent<HTMLElement>) => {
        ok?.onClick?.(event);
        handleOnSubmit();
      }
    } : {
      label: ok
    });
  }, [
    ok,
    handleOnSubmit
  ]);

  const cancel = usePropsCancel();

  const cancelButtonProps = useMemo(() => {
    return (typeof cancel === "object" ? {
      ...cancel,
      onClick: (event: MouseEvent<HTMLElement>) => {
        cancel?.onClick?.(event);
        handleOnClose();
      }
    } : {
      label: cancel
    });
  }, [
    cancel,
    handleOnClose
  ]);

  return (
    <Space>
      {footerExtra.map(button => {
        return (
          <React.Fragment key={button.key || Math.random()}>
            {button}
          </React.Fragment>
        );
      })}

      <Button
        onClick={handleOnClose}
        {...okButtonProps}>
        {typeof cancel === "string" ? cancel : cancel?.label || "关闭"}
      </Button>

      {isSubmit && (
        <Button
          {...cancelButtonProps}
          loading={locked === ModelLockState.LOADING}
          onClick={handleOnSubmit}
          type="primary">
          {typeof ok === "string" ? ok : ok?.label || "提交"}
        </Button>
      )}
    </Space>
  );
}
