// packages-vue/vue-element-plus-extra/src/dialog/model/provider/index.vue
<script lang="ts" setup>
import {
  defineProps,
  ref,
  unref
} from "vue";

import Context from "../context/index.vue";
import Lifecycle from "../lifecycle/index.vue";
import reducer from "../reducer";
import {
  IDialogProps,
  IModelState,
  TModelAction
} from "../types";
import {
  getDefaultContextState
} from "../utils";

const {
  props
} = defineProps<{
  props: IDialogProps;
}>();

const state = ref<IModelState>(getDefaultContextState(props));

/**
 * 表单实例
 */

const dispatch = (action: TModelAction): void => {
  state.value = reducer(unref(state), action);
};
</script>

<template>
  <Context
    :props="props"
    :dispatch="dispatch"
    :state="state"
  >
    <slot></slot>
    <Lifecycle />
  </Context>
</template>

// packages-react/react-ant-design-extra/src/rc-dialog/model/provider/index.tsx
import React, {
  useReducer
} from "react";

import Context from "../context";
import Lifecycle from "../lifecycle";
import reducer from "../reducer";
import {
  IModelProviderProps
} from "../types";
import {
  getDefaultContextState
} from "../util";

export default function Provider({
  children,
  props
}: IModelProviderProps): React.ReactNode {
  const [
    state,
    dispatch
  ] = useReducer(reducer, getDefaultContextState(props));

  return (
    <Context.Provider value={{
      state,
      dispatch,
      props
    }}>
      {children}
      <Lifecycle />
    </Context.Provider>
  );
}
